### ISSUE TITLE
gcc 4.6.2 referenced in developer's manual obsolete

### ISSUE THREAD

**Issue by iltis42** [XCSoar/XCSoar#755]
Looks like we need to update the handbook, there is no way to compile with gcc 4.6.2 today :)

~/XCSoar$ make
  CXX     output/UNIX/dbg/src/io/MapFile.o
In file included from ./src/Profile/ProfileMap.hpp:28,
                 from ./src/Profile/Profile.hpp:29,
                 from src/io/MapFile.cpp:26:
./src/util/Compiler.h:70:6: error: #error Sorry, your gcc version is too old. You need at least version 10.
   70 | #    error Sorry, your gcc version is too old.  You need at least version 10.
      |      ^~~~~
make: *** [build/compile.mk:108: output/UNIX/dbg/src/io/MapFile.o] Error 1

**Comment by lordfolken** [comment]
If you need a compile environment, we have a container here: https://github.com/XCSoar/XCSoar/tree/master/ide/docker

**Comment by MaxKellermann** [comment]
4.6.2? That has been removed from the manual in commit d1bc323cb9892296e071915b423056e2e810f864 (march 2020)
