### ISSUE TITLE
Does not compile with gcc 9.2.0

### ISSUE THREAD

**Issue by 1183519e** [XCSoar/XCSoar#280]
I run Arch Linux with gcc 9.2.0, arm-linux-gnueabihf-gcc 9.1.0-2.

`make TARGET=KOBO output/KOBO/KoboRoot.tgz` quits with:

>   CXX     output/KOBO/dbg/src/HorizonWidget.o
> In file included from ./src/Screen/Bitmap.hpp:32,
>                  from src/Look/VarioLook.hpp:30,
>                  from src/Look/Look.hpp:30,
>                  from src/HorizonWidget.cpp:26:
> ./src/Screen/Memory/PixelTraits.hpp: In static member function 'static constexpr GreyscalePixelTraits::color_type* GreyscalePixelTraits::NextByte(GreyscalePixelTraits::pointer_type, int)':
> ./src/Screen/Memory/PixelTraits.hpp:143:12: error: a reinterpret_cast is not a constant expression
>   143 |     return pointer_type((uint8_t *)p + delta);
>       |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ./src/Screen/Memory/PixelTraits.hpp: In static member function 'static constexpr const color_type* GreyscalePixelTraits::NextByte(GreyscalePixelTraits::const_pointer_type, int)':
> ./src/Screen/Memory/PixelTraits.hpp:148:12: error: a reinterpret_cast is not a constant expression
>   148 |     return const_pointer_type((const uint8_t *)p + delta);
>       |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> make: *** [build/compile.mk:108: output/KOBO/dbg/src/HorizonWidget.o] Error 1
